console.log("hello friends");
let name ="rahul kumar" ;
console.log(name  +" is a good boy");
//use of function
function greet(name ,greetText){
    console.log( greetText +  "   " + name);
    console.log(name    +   " is a good boy");

}
let name1="sohan";
let name2="rohan";
let name3="mohan";
let name4="pohan";
let greetText ="good morning";

greet(name1,greetText);
greet(name2,greetText);
greet(name3,greetText);
greet(name4,greetText);
